var section = {
	/*home default index*/
	"作者推荐":[4,9,2,0,1,11], 
	/*=================*/
	"读书杂记":[4,12,2,0,5,1],
	/*-----------------*/
	"文学小说":[0,1,5],
	"歌戏影视":[4],
	"奇技赢巧":[2,12],
	/*=================*/
	"科研技能":[3,14,13,15], /*note: article 14 and 13 顺序乱了*/
	/*-----------------*/
	"Py点云库":[3],
  "Py三维库":[14,13,15],
	"科研作图":[],
	"数据处理":[],
	"统计分析":[],
  "论文写作":[],
	/*=================*/
	"兴趣爱好":[9,11],
	/*-----------------*/
	"诗词歌赋":[9,11,10,8,7,6],
	"音乐乐理":[],
	"游戏心得":[]
};

var jsdb = [
{
"id":"0",
"title":"以爱之名，葬汝所幸",
"subtitle":"——《穆斯林的葬礼》读后感<br>如果他们继续阻挠你的选择，不妨告诉他们，不要以爱的名义去阻挠你的选择，因为，你的人生是你自己的，你的后悔也是你自己承受的，他们无法代替你自己去后悔。",
"author":"浩瀚猫",
"word":"2.6k",
"date":"2015.11.16",
"img":"img/page-heading/musilin.jpg",
"recommend":[1,4,5]
},
{
"id":"1",
"title":"生死随行，偿逝之殇",
"subtitle":"——《挪威的森林》读后感<br>人生好比舞台，有人会与你同台，也会有人提前退场，无需纠结谁会与你同台到最后，因为这是一个没有剧本的舞台，所能做的就是，到最后落幕的时候，演出了真正的自己，演出了让自己不会后悔的一出精彩的戏",
"author":"浩瀚猫",
"word":"1.1k",
"date":"2015.03.22",
"img":"img/page-heading/norway_forest.jpg",
"recommend":[0,4,5]
},
{
"id":"2",
"title":"我的雅思备考方法",
"subtitle":"有志者，事竟成，破釜沉舟，百二秦关终属楚；<br>苦心人，天不负，卧薪尝胆，三千越甲可吞吴。",
"author":"浩瀚猫",
"word":"4.6k",
"date":"2015.09.19",
"img":"img/page-heading/IELTS.jpg",
"recommend":[3]
},
{
"id":"3",
"title":"起步：Win10平台python-pcl环境搭建",
"subtitle":"开源带来的最明显变化，就是从公司开发人员头发逐渐消失，变为所有用户头发一起逐渐消失。",
"author":"浩瀚猫",
"word":"5.4k",
"date":"2018.05.08",
"img":"img/page-heading/point_cloud0.jpg",
"recommend":[2,13]
},
{
"id":"4",
"title":"娱乐尽头，皆是虚妄", 
"subtitle":"——《头号玩家》影评<br>不要被麻醉剂麻痹了神经，不断提高自身能力与打磨心性，利用越来越窄的阶级上升通道向上攀爬，毕竟短短的人类文明还没有把弱肉强食从漫长的生物进化过程中抹去的能力。",
"author":"浩瀚猫",
"word":"2k",
"date":"2018.05.10",
"img":"img/page-heading/ready_player_one.jpg",
"recommend":[0,1,5]
},
{"id":"5",
"title":"守望者究竟在麦田守望啥", 
"subtitle":"——《麦田里的守望者》读后感<br>学校教育除了能让你变得博学谦逊之外，慢慢的，你就会发现你的脑子对什么合适，这可以节省你不少时间，免得你去瞎试一些对你不合适、不贴切的思想，慢慢就会知道如何恰如其分的把你的头脑武装起来。",
"author":"浩瀚猫",
"word":"835",
"date":"2015.03.26",
"img":"img/page-heading/wheatland.jpg",
"recommend":[0,1,4]
},
{"id":"6",
"title":"咏梅●藏头", 
"subtitle":"——致黄艳梅与唐雨琦",
"author":"浩瀚猫",
"word":"28",
"date":"2014.05.26",
"img":"img/page-heading/wintersweet.jpg",
"recommend":[9,7,8]
},
{"id":"7",
"title":"与君勉●藏头", 
"subtitle":"——致肖雨芯十九诞辰",
"author":"浩瀚猫",
"word":"28",
"date":"2014.05.18",
"img":"img/page-heading/swan.jpg",
"recommend":[9,6,8]
},
{"id":"8",
"title":"燕●藏头", 
"subtitle":"——谢敏譞唐雨琦，跟吾三人诞辰之日相连也，遂成诗",
"author":"浩瀚猫",
"word":"96",
"date":"2014.08.20",
"img":"img/page-heading/birthday.jpg",
"recommend":[9,6,7]
},
{"id":"9",
"title":"水调歌头●中秋", 
"subtitle":"乙未中秋，与友操场赏月畅谈，返室饮酒微醺，作此篇。",
"author":"浩瀚猫",
"word":"349",
"date":"2015.09.27",
"img":"img/page-heading/mid-autumn.jpg",
"recommend":[11]
},
{"id":"10",
"title":"绝句", 
"subtitle":"——“可是跟你走的那一段路好短，短到我来不及鼓起勇气告诉你这份可爱可恨的小情愫”",
"author":"浩瀚猫",
"word":"28",
"date":"2015.10.08",
"img":"img/page-heading/jiao5.jpg",
"recommend":[9]
},
{"id":"11",
"title":"江城子●结荃一载", 
"subtitle":"轻轻的你走了，正如你轻轻的来。",
"author":"浩瀚猫",
"word":"131",
"date":"2016.10.29",
"img":"img/page-heading/farewell.jpg",
"recommend":[9]
},
{"id":"12",
"title":"UNB-ELP考试资料", 
"subtitle":"绝密●启用前",
"author":"浩瀚猫",
"word":"1.2k",
"date":"2016.12.8",
"img":"img/page-heading/IELTS.jpg",
"recommend":[2,3]
},
{"id":"13",
"title":"第二章 三维可视之TVTK基础", 
"subtitle":"用一个看歌剧小故事类比TVTK库的工作流程(管线)，介绍了TVTK支持的数据格式与数据加载，以及简单的TVTK可视化范例。",
"author":"浩瀚猫",
"word":"3.3k",
"date":"2018.12.05",
"img":"img/page-heading/three_d_visualization.jpg",
"recommend":[14,15]
},
{"id":"14",
"title":"第一章 三维可视之前奏",
"subtitle":"主要介绍了三维可视化基础，以及三维可视化的Python环境搭建。",
"author":"浩瀚猫",
"word":"707",
"date":"2018.12.06",
"img":"img/page-heading/three_d_visualization.jpg",
"recommend":[13,15]
},
{"id":"15",
"title":"第三章 三维可视之Mayavi基础",
"subtitle":"介绍了利用MayaVi库里面的Mlab模块，实现了科学数据(就是通过一堆复杂的一逼的数学公式算出来的数据)的三维可视化和使用三维模型(非科学数据)的应用级交互操作",
"author":"浩瀚猫",
"word":"6.8k",
"date":"2018.12.15",
"img":"img/page-heading/three_d_visualization.jpg",
"recommend":[14,13]
}
];